# Generated by Django 4.2 on 2023-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_board1_permission_user_board2_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='board1_permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='board2_permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='board3_permission',
        ),
        migrations.AddField(
            model_name='user',
            name='board_permissions',
            field=models.CharField(blank=True, choices=[('1', 'Board1'), ('2', 'Board2'), ('3', 'Board3')], max_length=1, null=True),
        ),
    ]
