# Generated by Django 4.2 on 2023-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_board1_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='board_permissions',
            field=models.CharField(blank=True, choices=[('0', 'No Board'), ('1', 'Board1'), ('2', 'Board2'), ('3', 'Board3'), ('4', 'All Board')], max_length=1, null=True),
        ),
    ]
