# Generated by Django 4.2 on 2023-04-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('month_number', models.CharField(max_length=11, unique=True, verbose_name='월번호')),
                ('title', models.CharField(default='DEFAULT', max_length=100)),
                ('content', models.TextField(default='DEFAULT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
