# Generated by Django 4.2 on 2023-04-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board2', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board2',
            name='id',
        ),
        migrations.AlterField(
            model_name='board2',
            name='month_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
