# Generated by Django 4.2 on 2023-05-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board1.additionalfield')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_data', to='board1.board1')),
            ],
            options={
                'unique_together': {('post', 'field')},
            },
        ),
    ]
