# Generated by Django 4.2 on 2023-04-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board1', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board1',
            name='board_mapping',
        ),
    ]
